{{
	config(
		materialized = "incremental"
	)
}}

with
    rtr_ins_upd_exp_ins as (
        select *
        from {{ ref("m_atomic_cml_agmt_upd_cesar_rtr_ins_upd") }}
        where out_expins_upd_flag = 'I'
    ),
    fil_chng_cml_agmt as (
        select
            out_cml_chng_flg as cml_chng_flg,
            cml_agmt_id,
            agmt_anchr_id,
            pol_nbr,
            pol_eff_dt,
            typ_id,
            actv_rec_ind,
            inmy_agmt_anchr_id,
            acqn_cd,
            adt_freq_cd,
            bndl_cd,
            can_dt,
            can_rsn_cd,
            ciid_match_ind,
            cms_pty_id,
            cpan_ind,
            cust_nbr,
            dac_cd,
            divd_par_cd,
            exc_cd,
            instl_cd,
            modu_nbr,
            mp_cd,
            plnd_end_dt,
            pol_contr_typ_cd,
            pol_sym_cd,
            port_ind,
            pri_nmd_insd_nm,
            prcg_ofc_cd,
            prdr_src_cd,
            ratg_ori_cd,
            reins_waqs_trty_cd,
            renl_ind,
            retro_ratg_cd,
            rsk_typ_cd,
            self_insd_retn_ind,
            sic_cd,
            src_pol_nbr,
            src_pol_eff_dt,
            src_pol_sym_cd,
            sts_cd,
            undg_pgm_cd,
            v_inv_pool_ind,
            eff_fm_tistmp,
            eff_to_tistmp,
            bil_typ_cd,
            incp_dt,
            agmt_term_in_mnth,
            contr_type_cd,
            mkt_cd,
            perf_prot_ind,
            sale_dt,
            pymt_pln_cd,
            mstr_pol_nbr,
            tail_expi_dt,
            src_mstr_pol_nbr,
            src_pymt_pln_cd,
            src_ext_rpt_perd_dt,
            out_eff_to_tistmp,
            out_eff_fm_tistmp,
            out_batch_id,
            out_pop_info_id,
            polhldr_entprs_id,
            polhldr_site_duns_nbr,
            out_mstr_pol_cd as out_mstr_pol_cd3,
            out_src_wc_ratg_bas_cd as out_src_wc_ratg_bas_cd3,
            pri_nmd_insd_fein_nbr as pri_nmd_insd_fein_nbr3,
            out_ptnr_ctry_pol_id as assm_ptnr_ctry_pol_id3,
            out_ptnr_ctry_pol_nbr as assm_us_pol_nbr3,
            out_plc_anchr_id as cede_ptnr_ctry_anchr_id3,
            out_pol_lvl_crcy_cd as drvd_contr_crcy_cd3,
            out_frntg_cd as frnt_cd3,
            out_non_renl_rsn_cd as non_renl_rsn_cd3,
            out_ips_contr_id as zi_pol_sys_contr_id3,
            genl_ln_of_busn_cd as genl_ln_of_busn_cd3,
            frgn_prdr_cd as frgn_prdr_cd3
        from rtr_ins_upd_exp_ins
        where cml_chng_flg = 'U'
    ),
    exp_set_val_cml_agmt as (
        select
            cml_agmt_id,
            out_eff_fm_tistmp as eff_fm_tistmp,
            out_pop_info_id as pop_info_id,
            out_batch_id as batch_id,
            agmt_anchr_id,
            pol_nbr,
            pol_eff_dt,
            typ_id,
            actv_rec_ind,
            inmy_agmt_anchr_id,
            acqn_cd,
            adt_freq_cd,
            bndl_cd,
            can_dt,
            can_rsn_cd,
            ciid_match_ind,
            cms_pty_id,
            cpan_ind,
            cust_nbr,
            dac_cd,
            divd_par_cd,
            exc_cd,
            instl_cd,
            modu_nbr,
            mp_cd,
            plnd_end_dt,
            pol_contr_typ_cd,
            pol_sym_cd,
            port_ind,
            pri_nmd_insd_nm,
            prcg_ofc_cd,
            prdr_src_cd,
            ratg_ori_cd,
            reins_waqs_trty_cd,
            renl_ind,
            retro_ratg_cd,
            rsk_typ_cd,
            self_insd_retn_ind,
            sic_cd,
            src_pol_nbr,
            src_pol_eff_dt,
            src_pol_sym_cd,
            sts_cd,
            undg_pgm_cd,
            v_inv_pool_ind,
            eff_fm_tistmp as eff_fm_tistmp1,
            eff_to_tistmp,
            pop_info_id as pop_info_id1,
            updt_pop_info_id,
            bat_id,
            bil_typ_cd,
            incp_dt,
            agmt_term_in_mnth,
            contr_type_cd,
            mkt_cd,
            perf_prot_ind,
            sale_dt,
            pymt_pln_cd,
            mstr_pol_nbr,
            tail_expi_dt,
            src_mstr_pol_nbr,
            src_pymt_pln_cd,
            src_ext_rpt_perd_dt,
            out_eff_to_tistmp,
            out_eff_fm_tistmp,
            out_batch_id,
            out_pop_info_id,
            polhldr_entprs_id,
            polhldr_site_duns_nbr,
            out_mstr_pol_cd3 as mstr_pol_cd,
            out_src_wc_ratg_bas_cd3 as src_wc_ratg_bas_cd,
            pri_nmd_insd_fein_nbr3 as pri_nmd_insd_fein_nbr,
            'N' as out_actv_rec_ind,
            'CML_AGMT' as out_table_name,
            11043 as out_step_key,
            'm_ATOMIC_CML_AGMT_UPD_CESAR' as out_process_name,
            'STS_DESC' as out_sts_desc,
            -- *INF*: ADD_TO_DATE(SESSSTARTTIME,'SS',-1)
            dateadd(second, - 1, sessstarttime) as out_eff_to_tistmp_upd,
            -1 as out_mkt_prdt_spec_id,
            assm_ptnr_ctry_pol_id3,
            assm_us_pol_nbr3,
            cede_ptnr_ctry_anchr_id3,
            drvd_contr_crcy_cd3,
            frnt_cd3,
            non_renl_rsn_cd3,
            zi_pol_sys_contr_id3,
            genl_ln_of_busn_cd3,
            frgn_prdr_cd3
        from fil_chng_cml_agmt
    )
select
    cml_agmt_id as surrogate_key,
    out_actv_rec_ind as actv_rec_ind,
    out_eff_to_tistmp_upd as eff_to_tistmp,
    pop_info_id as updt_pop_info_id,
    out_table_name as table_name,
    out_step_key as step_key,
    out_process_name as process_name,
    batch_id as bat_id
from exp_set_val_cml_agmt
