
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'infa2dbt'
version: '1.0.0'
config-version: 2

vars:
  czc_startdate : '2024-01-01 00:00:00'
  pop_info_id :  '101' 
  batch_id   :   '301'
  dbownerprst: 'infa2dbt'
  tbl_tech_nm: 'WRK_ACTU_LRC_FINC_CMPNT_EXTRACT'
  ml_finc_prd: '202310'
  dbownerwrk: 'infa2dbt'
  seq_acct_anchr_id: '100'


# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  infa2dbt:
    czc_src_cdc:
      m_cdc_cc_user:
        +database: infa2dbt
        +materialized: table
        +schema: DBAALL